// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdfzWPjMyFhlD_Go3zDd_lyk-pKe3GFeM',
    appId: '1:722492027654:web:cc797809782d19961b6487',
    messagingSenderId: '722492027654',
    projectId: 'lensfix-cde1e',
    authDomain: 'lensfix-cde1e.firebaseapp.com',
    storageBucket: 'lensfix-cde1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6X-56LI9jarNZpwud8aEOkNHC2g1lp4w',
    appId: '1:722492027654:android:f5b0ecd542977aa41b6487',
    messagingSenderId: '722492027654',
    projectId: 'lensfix-cde1e',
    storageBucket: 'lensfix-cde1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_OHngpBKEV0vg6wCFOH4OslR16BWsoo',
    appId: '1:722492027654:ios:c1ddf04574e573141b6487',
    messagingSenderId: '722492027654',
    projectId: 'lensfix-cde1e',
    storageBucket: 'lensfix-cde1e.firebasestorage.app',
    iosBundleId: 'com.example.lensFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_OHngpBKEV0vg6wCFOH4OslR16BWsoo',
    appId: '1:722492027654:ios:c1ddf04574e573141b6487',
    messagingSenderId: '722492027654',
    projectId: 'lensfix-cde1e',
    storageBucket: 'lensfix-cde1e.firebasestorage.app',
    iosBundleId: 'com.example.lensFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdfzWPjMyFhlD_Go3zDd_lyk-pKe3GFeM',
    appId: '1:722492027654:web:78666e48edea50211b6487',
    messagingSenderId: '722492027654',
    projectId: 'lensfix-cde1e',
    authDomain: 'lensfix-cde1e.firebaseapp.com',
    storageBucket: 'lensfix-cde1e.firebasestorage.app',
  );
}
